import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { NextUiProviders } from "../providers/next-ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NextUiProviders>
            <NavBar />
            <main className="md:mt-20 mt-12 w-full min-h-screen">
              {children}
            </main>
          </NextUiProviders>
      </body>
    </html>
  );
}
